server:
  port: 8081

spring:
  application:
    name: mock-banking-api
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
  show-actuator: false
