package com.testforge.runner.report;

import com.testforge.runner.model.ExecutionReport;
import com.testforge.runner.report.sections.*;

import java.util.List;

public class HtmlReportGenerator {

    private final List<ReportSection> sections;
    private final NavigationRenderer navigationRenderer;

    public HtmlReportGenerator() {
        this.sections = List.of(
                new SummarySection(),
                new ConsistencySection(),
                new ScenarioSection(),
                new ApiSection(),
                new FailureAnalysisSection()
        );
        this.navigationRenderer = new NavigationRenderer();
    }

    public String generate(ExecutionReport report) {
        StringBuilder html = new StringBuilder();
        html.append(renderHead());
        html.append("<body>\n");
        html.append(navigationRenderer.render(sections, report));
        html.append("<main class=\"report-content\">\n");
        html.append("<h1>TestForge AI Execution Report</h1>\n");

        for (ReportSection section : sections) {
            if (section.hasContent(report)) {
                html.append("<section id=\"").append(section.getSectionId()).append("\">\n");
                html.append("<h2>").append(section.getIcon()).append(" ").append(section.getNavLabel()).append("</h2>\n");
                html.append(section.render(report));
                html.append("</section>\n");
            }
        }

        html.append("</main>\n");
        html.append("<footer>Generated by TestForge AI &middot; github.com/meiashley/testforge-ai</footer>\n");
        html.append("</body>\n</html>");
        return html.toString();
    }

    private String renderHead() {
        return "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
                + "<meta charset=\"UTF-8\">\n"
                + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "<title>TestForge AI - Execution Report</title>\n"
                + "<style>\n"
                + "*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n"
                + "body { font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif;"
                + " background: #f1f5f9; color: #1e293b; padding: 24px; max-width: 1100px; margin: 0 auto; }\n"
                + "h1 { font-size: 1.75rem; color: #1e40af; margin-bottom: 4px; }\n"
                + "h2 { font-size: 1.1rem; color: #1e40af; margin: 24px 0 12px; }\n"
                + "h3 { font-size: 0.95rem; color: #1e40af; margin: 12px 0 6px; }\n"
                + ".meta { color: #6b7280; font-size: 0.875rem; margin-bottom: 24px; }\n"
                + ".cards { display: flex; gap: 16px; flex-wrap: wrap; margin-bottom: 24px; }\n"
                + ".card { background: #fff; border-radius: 8px; padding: 20px 24px;"
                + " box-shadow: 0 1px 3px rgba(0,0,0,.1); min-width: 130px; flex: 1; }\n"
                + ".card .label { font-size: 0.75rem; color: #6b7280; text-transform: uppercase;"
                + " letter-spacing: .05em; margin-bottom: 6px; }\n"
                + ".card .value { font-size: 2rem; font-weight: 700; }\n"
                + ".card.rate .value { color: #16a34a; }\n"
                + "details { background: #fff; border-radius: 8px; margin-bottom: 8px;"
                + " box-shadow: 0 1px 3px rgba(0,0,0,.1); overflow: hidden; }\n"
                + "details[open] { padding-bottom: 16px; }\n"
                + "summary { padding: 12px 16px; cursor: pointer; font-size: 0.9rem;"
                + " display: flex; align-items: center; gap: 12px; user-select: none; }\n"
                + "summary:hover { background: #f8fafc; }\n"
                + "summary.failed { background: #fee2e2; }\n"
                + "summary.failed:hover { background: #fecaca; }\n"
                + ".badge { display: inline-block; padding: 2px 8px; border-radius: 9999px;"
                + " font-size: 0.7rem; font-weight: 600; text-transform: uppercase; }\n"
                + ".badge-HAPPY_PATH { background: #dbeafe; color: #1e40af; }\n"
                + ".badge-BOUNDARY { background: #ede9fe; color: #6d28d9; }\n"
                + ".badge-NEGATIVE { background: #fed7aa; color: #c2410c; }\n"
                + ".badge-SECURITY { background: #fecaca; color: #991b1b; }\n"
                + ".details-body { padding: 0 16px; }\n"
                + "pre { background: #f8fafc; padding: 12px; border-radius: 6px;"
                + " overflow-x: auto; font-size: 0.8rem; line-height: 1.4;"
                + " border: 1px solid #e2e8f0; }\n"
                + "table.assertions { width: 100%; border-collapse: collapse; margin-top: 4px; }\n"
                + "table.assertions th { background: #1e40af; color: #fff; text-align: left;"
                + " padding: 6px 10px; font-size: 0.75rem; text-transform: uppercase; }\n"
                + "table.assertions td { padding: 6px 10px; font-size: 0.825rem;"
                + " border-bottom: 1px solid #f1f5f9; vertical-align: top; }\n"
                + "table.assertions tr.assert-failed { background: #fef2f2; }\n"
                + "code { font-family: SFMono-Regular, Menlo, Monaco, Consolas, monospace;"
                + " font-size: 0.85em; }\n"
                + ".name { flex: 1; }\n"
                + ".meta-info { color: #6b7280; font-size: 0.75rem; }\n"
                + "footer { margin-top: 32px; text-align: center; color: #6b7280; font-size: 0.8rem; }\n"
                // AI Analysis styles
                + ".ai-analysis-details { background: #f0f9ff; border: 1px solid #bae6fd;"
                + " border-radius: 8px; margin-top: 16px; box-shadow: none; }\n"
                + ".ai-analysis-details[open] { padding-bottom: 12px; }\n"
                + ".ai-analysis-summary { background: #e0f2fe; border-radius: 8px; font-size: 0.85rem;"
                + " font-weight: 600; color: #0369a1; padding: 10px 14px; gap: 10px; }\n"
                + ".ai-analysis-summary:hover { background: #bae6fd; }\n"
                + ".ai-analysis-body { padding: 12px 16px 0; display: flex; flex-direction: column; gap: 10px; }\n"
                + ".ai-header { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }\n"
                + ".category-badge { display: inline-block; padding: 3px 10px; border-radius: 9999px;"
                + " font-size: 0.72rem; font-weight: 700; text-transform: uppercase; color: #fff; }\n"
                + ".category-TEST_LOGIC_ERROR { background: #dc2626; }\n"
                + ".category-API_BUG { background: #9333ea; }\n"
                + ".category-ASSERTION_TOO_STRICT { background: #ea580c; }\n"
                + ".category-DATA_DEPENDENCY { background: #2563eb; }\n"
                + ".category-ENVIRONMENT { background: #6b7280; }\n"
                + ".category-UNCERTAIN { background: #ca8a04; }\n"
                + ".confidence-badge { display: inline-block; padding: 3px 10px; border-radius: 9999px;"
                + " font-size: 0.72rem; font-weight: 700; text-transform: uppercase; color: #fff; }\n"
                + ".confidence-HIGH { background: #16a34a; }\n"
                + ".confidence-MEDIUM { background: #ca8a04; }\n"
                + ".confidence-LOW { background: #6b7280; }\n"
                + ".ai-field { font-size: 0.85rem; line-height: 1.5; color: #1e293b; }\n"
                + ".ai-field strong { color: #0369a1; }\n"
                // Consistency badges
                + ".severity-badge { display: inline-block; padding: 2px 8px; border-radius: 9999px;"
                + " font-size: 0.7rem; font-weight: 700; text-transform: uppercase; color: #fff; }\n"
                + ".severity-HIGH { background: #dc2626; }\n"
                + ".severity-MEDIUM { background: #f59e0b; }\n"
                + ".severity-LOW { background: #6b7280; }\n"
                + ".category-mm-badge { display: inline-block; padding: 2px 8px; border-radius: 9999px;"
                + " font-size: 0.7rem; font-weight: 700; text-transform: uppercase; color: #fff; }\n"
                + ".category-mm-MISSING_IN_API { background: #7c3aed; }\n"
                + ".category-mm-UNDOCUMENTED_API { background: #2563eb; }\n"
                + ".category-mm-CONSTRAINT_CONFLICT { background: #ea580c; }\n"
                + ".category-mm-AMBIGUOUS_REQUIREMENT { background: #ca8a04; }\n"
                + ".category-mm-WORKFLOW_MISMATCH { background: #dc2626; }\n"
                // Navigation bar
                + ".report-nav { position: sticky; top: 0; background: #fff; z-index: 100;"
                + " display: flex; gap: 8px; padding: 12px 0; border-bottom: 1px solid #e2e8f0;"
                + " margin-bottom: 24px; flex-wrap: wrap; }\n"
                + ".report-nav a { display: inline-flex; align-items: center; gap: 6px;"
                + " padding: 6px 14px; border-radius: 9999px; background: #f1f5f9; color: #1e293b;"
                + " text-decoration: none; font-size: 0.875rem; font-weight: 500;"
                + " transition: background 0.15s; }\n"
                + ".report-nav a:hover { background: #dbeafe; color: #1e40af; }\n"
                + ".report-content section { margin-bottom: 40px; scroll-margin-top: 64px; }\n"
                + "@media (max-width: 640px) { .cards { flex-direction: column; }"
                + " summary { flex-wrap: wrap; } body { padding: 12px; } }\n"
                + "</style>\n</head>\n";
    }
}
